# Generated by Django 5.1.4 on 2024-12-11 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('vin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('oil', 'Moy almashtirish'), ('gasoline', 'Benzin quyish'), ('temperature', 'Dvigatel harorati')], max_length=50)),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil_change', 'Moy almashtirish'), ('gasoline_refill', 'Benzin quyish'), ('engine_temp', 'Dvigatel harorati')], max_length=100)),
                ('scheduled_date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicles')),
            ],
        ),
    ]
